baseURL = '/'
languageCode = 'en-us'
title = 'IC Dependency Jamboree'
defaultContentLanguage = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
section = ["HTML"]

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[params]
copyright = "IdeaCrew, Inc."
offlineSearch = false

[params.ui]
sidebar_menu_compact = false
sidebar_search_disable = false

[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = ["tags", "categories"]

# If used, must have same length as taxonomyCloud
taxonomyCloudTitle = ["Tag Cloud", "Categories"]

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["tags", "categories"]

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
