# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'aca_entities',  git:  'https://github.com/ideacrew/aca_entities.git', branch: 'trunk'
gem 'event_source',  git:  'https://github.com/ideacrew/event_source.git', branch: 'trunk'
gem 'resource_registry',  git:  'https://github.com/ideacrew/resource_registry.git', branch: 'trunk'
gem 'acapi', git: "https://github.com/ideacrew/acapi.git", branch: 'trunk'

# This file mirrors the current constraints in Enroll trunk, to see if it is
# compatible with our latest versions.

# Right now we include, bit by bit, the constraints we *know* will fail.
gem 'nokogiri', '~> 1.10.8'
gem 'nokogiri-happymapper', '~> 0.8.0', :require => 'happymapper'
gem 'openhbx_cv2', git:  'https://github.com/ideacrew/openhbx_cv2.git', branch: 'trunk'

gem 'rails', '~> 5.2.4.3'
gem 'bson',                     '~> 4.3'
gem 'mongoid',                  '~> 7.0.2'
gem 'mongo',                    '~> 2.6'
gem 'mongo_session_store',      '~> 3.1'
gem 'mongoid-autoinc',          '~> 6.0'
gem 'mongoid-history',          '~> 0.8'
gem 'mongoid_rails_migrations', '~> 1.2'
gem 'aasm',                     '~> 4.8'
gem 'redis',                    '~> 4.0'
gem 'redis-rails',              '~> 5.0.2'
gem 'resque',                   '~> 1.26.0'
gem 'loofah', '~> 2.3.1'