# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'aca_entities',  git:  'https://github.com/ideacrew/aca_entities.git', branch: 'trunk'
gem 'event_source',  git:  'https://github.com/ideacrew/event_source.git', branch: 'trunk'
gem 'resource_registry',  git:  'https://github.com/ideacrew/resource_registry.git', branch: 'trunk'
gem 'acapi', git: "https://github.com/ideacrew/acapi.git", branch: 'trunk'

# This file mirrors the current constraints in Enroll trunk, to see if it is
# compatible with our latest versions.

# Right now we include, bit by bit, the constraints we *know* will fail.
gem 'nokogiri', '~> 1.10.8'
gem 'openhbx_cv2', git:  'https://github.com/ideacrew/openhbx_cv2.git', branch: 'trunk'
