# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'aca_entities',  git:  'https://github.com/ideacrew/aca_entities.git', branch: 'trunk'
gem 'event_source',  git:  'https://github.com/ideacrew/event_source.git', branch: 'trunk'
gem 'resource_registry',  git:  'https://github.com/ideacrew/resource_registry.git', branch: 'trunk'

# Version constraints from the FTI Gemfile
gem 'dry-matcher',            '~> 0.8'
gem 'dry-monads',             '~> 1.3'
gem 'dry-schema',             '~> 1.6'
gem 'dry-struct',             '~> 1.4'
gem 'dry-transaction',        '~> 0.13'
gem 'dry-types',              '~> 1.5'
gem 'dry-validation',         '~> 1.6'

gem 'redis', '~> 4.0'