name: Test Bundler
on: 
  workflow_dispatch:
  push:

jobs:
  test-bundler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - name: bundle install
        run: |
          bundle install
