name: Test Bundler
on:
  workflow_dispatch:
  push:

jobs:
  test-bundler-base:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ['2.6.3', '2.7.5', '3.0.5', '3.1.4', '3.2.2']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - name: bundle install
        run: |
          cd base
          bundle install
  test-bundler-enroll:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ['2.6.3', '2.7.5', '3.0.5', '3.1.4', '3.2.2']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - name: bundle install
        run: |
          cd enroll
          bundle install
  test-bundler-fti:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ['2.6.3', '2.7.5', '3.0.5', '3.1.4', '3.2.2']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - name: bundle install
        run: |
          cd fti
          bundle install
  test-bundler-fdsh-gateway:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ['2.6.3', '2.7.5', '3.0.5', '3.1.4', '3.2.2']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - name: bundle install
        run: |
          cd fdsh_gateway
          bundle install
  test-bundler-edi-gateway:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ['2.6.3', '2.7.5', '3.0.5', '3.1.4', '3.2.2']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - name: bundle install
        env:
          BUNDLE_GITHUB__COM: "x-access-token:${{ secrets.GH_PAT }}"
        run: |
          cd edi_gateway
          bundle install